server:
  port: 9494

spring:
  application:
    name: spring-openai-demo

  main:
    web-application-type: NONE
    banner-mode: OFF

  ai:
    openai:
      api-key: ${OPEN_API_KEY}

    mcp:
      server:
        enabled: true
        name: ai-support-mcp
        type: SYNC
        stdio: true

  datasource:
    url: jdbc:postgresql://localhost:5432/customer-support
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update   # auto create/update tables
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: OFF